spring.application.name=project-management-api
server.port=${PORT:8080}

# Supabase Database Connection
spring.datasource.url=jdbc:postgresql://db.roexkweeuplxkpjiuojc.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=944121@qazWS

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false